# Python : Pengenalan Numpy dan Pandas

## Numpy
Numerical Python (Numpy) merupakan package dasar yang diperlukan dalam pemrograman scientific dengan Python.

Numpy merupakan library Python yang mencakup beragam objek terkait multidimensional array. mencakup juga mathematical, logical, shape manipulation, sorting, selecting, serta operasi lainnya.

### Numpy Installation

In [1]:
!pip show numpy

Name: numpy
Version: 1.22.4
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: /usr/local/lib/python3.10/dist-packages
Requires: 
Required-by: albumentations, altair, arviz, astropy, autograd, blis, bokeh, chex, cmdstanpy, contourpy, cufflinks, cvxpy, datascience, db-dtypes, dopamine-rl, ecos, flax, folium, gensim, gym, h5py, holoviews, hyperopt, imageio, imbalanced-learn, imgaug, jax, jaxlib, librosa, lightgbm, matplotlib, matplotlib-venn, missingno, mizani, ml-dtypes, mlxtend, moviepy, music21, nibabel, numba, numexpr, opencv-contrib-python, opencv-python, opencv-python-headless, opt-einsum, optax, orbax-checkpoint, osqp, pandas, pandas-gbq, patsy, plotnine, prophet, pyarrow, pycocotools, pyerfa, pymc, pytensor, python-louvain, PyWavelets, qdldl, qudida, scikit-image, scikit-learn, scipy, scs, seaborn, shapely, sklearn-pandas, soxr, spacy, statsmodels, tabl

In [2]:
import numpy as np

### Membuat Array

#### Manual dari List

In [3]:
lsdata = [a for a in range(100)]

In [4]:
arrdata = np.array(lsdata)

In [5]:
arrdata

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
arrdata.ndim

1

In [7]:
import random

In [8]:
lsdata1 = [[random.randint(0,100) for i in range(3)] for a in range(10)]

In [9]:
lsdata1

[[47, 83, 37],
 [37, 13, 53],
 [48, 38, 32],
 [40, 68, 13],
 [26, 29, 38],
 [10, 82, 68],
 [97, 15, 33],
 [31, 59, 45],
 [97, 29, 31],
 [33, 55, 27]]

In [10]:
arrdata1 = np.array(lsdata1, dtype=np.float32)

In [11]:
arrdata1.dtype

dtype('float32')

In [12]:
arrdata1.ndim

2

In [14]:
ls3d = [[[n for n in range(2)] for i in range(3)] for a in range(10)]

In [15]:
ls3d

[[[0, 1], [0, 1], [0, 1]],
 [[0, 1], [0, 1], [0, 1]],
 [[0, 1], [0, 1], [0, 1]],
 [[0, 1], [0, 1], [0, 1]],
 [[0, 1], [0, 1], [0, 1]],
 [[0, 1], [0, 1], [0, 1]],
 [[0, 1], [0, 1], [0, 1]],
 [[0, 1], [0, 1], [0, 1]],
 [[0, 1], [0, 1], [0, 1]],
 [[0, 1], [0, 1], [0, 1]]]

In [16]:
arr3d = np.array(ls3d)

In [17]:
arr3d.ndim

3

### Menggunakan Function

In [18]:
arr1 = np.arange(0,10)

In [19]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr2 = np.arange(0,30,2)

In [21]:
arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

## Indexing

In [23]:
arr1[2]

2

In [24]:
arr1[-2]

8

In [25]:
arr1[0:2]

array([0, 1])

In [26]:
arr1[:3]

array([0, 1, 2])

In [27]:
arr1[1:3]

array([1, 2])

In [28]:
arr_3 = np.array([[[1,2,3,4,5], [6,7,8,9,10]],[[2,4,6,8,10], [12,14,16,16,20]]])

In [29]:
arr_3.ndim

3

In [30]:
arr_3[1]

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 16, 20]])

In [31]:
arr_3[1][0]

array([ 2,  4,  6,  8, 10])

In [32]:
arr_3[1][0][0]

2

In [33]:
arr_3[1,0,0]

2

## Operation

In [34]:
arr1+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
arr1*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [36]:
arr1**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [37]:
arr1[0:6]+arr2[0:6]

array([ 0,  3,  6,  9, 12, 15])

In [38]:
arr1[0:6]*arr2[0:6]

array([ 0,  2,  8, 18, 32, 50])

## Statistik

In [39]:
arrdata1

array([[47., 83., 37.],
       [37., 13., 53.],
       [48., 38., 32.],
       [40., 68., 13.],
       [26., 29., 38.],
       [10., 82., 68.],
       [97., 15., 33.],
       [31., 59., 45.],
       [97., 29., 31.],
       [33., 55., 27.]], dtype=float32)

In [40]:
arrdata1.shape

(10, 3)

In [41]:
arrdata1.max()

97.0

In [42]:
arrdata1.min()

10.0

In [43]:
arrdata1.mean()

43.8

In [44]:
arrdata1.std()

23.15081

In [45]:
arrdata1.cumsum()

array([  47.,  130.,  167.,  204.,  217.,  270.,  318.,  356.,  388.,
        428.,  496.,  509.,  535.,  564.,  602.,  612.,  694.,  762.,
        859.,  874.,  907.,  938.,  997., 1042., 1139., 1168., 1199.,
       1232., 1287., 1314.], dtype=float32)

### Seberapa Cepat Numpy Array dibandingkan List

In [46]:
#https://www.geeksforgeeks.org/why-numpy-is-faster-in-python/
# importing required packages
import numpy
import time

# size of arrays and lists
size = 1000000

# declaring lists
list1 = range(size)
list2 = range(size)

# declaring arrays
array1 = numpy.arange(size)
array2 = numpy.arange(size)

# list
initialTime = time.time()
resultantList = [(a * b) for a, b in zip(list1, list2)]

# calculating execution time
print("Time taken by Lists :",
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
resultantArray = array1 * array2

# calculating execution time
print("Time taken by NumPy Arrays :",
	(time.time() - initialTime),
	"seconds")


Time taken by Lists : 0.11108136177062988 seconds
Time taken by NumPy Arrays : 0.004428386688232422 seconds
